version: "2"
linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unconvert
    - unused
    - sloglint
  settings:
    staticcheck:
      checks:
        - -SA1029
        - -SA4006
        - -ST1003
        - -ST1005
        - -ST1016
        - all
    sloglint:
      no-mixed-args: true
      attr-only: true
      context: scope
      static-msg: true
      msg-style: lowercased
      key-naming-case: snake
      args-on-sep-lines: true
      no-global: all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: by other packages, and that stutters; consider calling this
      - path: (.+)\.go$
        text: "var-naming:"
      - path: (.+)\.go$
        text: "receiver-naming:"
      - path: (.+)\.go$
        text: "unexported-return:"
      - path: (.+)\.go$
        text: "unused-parameter: parameter"
      - path: (.+)\.go$
        text: "context-keys-type: should not use basic type string"
      - path: (.+)\.go$
        text: error strings should not be capitalized
      - linters:
          - staticcheck
        text: "ST1003:"
    paths:
      - '(.+)_test\.go'
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/tuanvumaihuynh/victoria-o11y-lab
  exclusions:
    generated: disable
