package postgres

import (
	"strings"

	"github.com/exaring/otelpgx"
)

func newTracer() *otelpgx.Tracer {
	// Use global trace provider
	return otelpgx.NewTracer(
		otelpgx.WithSpanNameFunc(queryName),
	)
}

// queryName looks to see if the query has a name and returns it.
// It does this by looking for a prefixed comment on the SQL query,
// which means it supports SQLC out of the box.
//
// Formats supported listed in order of performance parsing:
// -- name: {name} :{type}
// -- name:{name}
// -- name: {name}
//
// ref: https://github.com/exaring/otelpgx/issues/47#issuecomment-2876346313
func queryName(q string) string {
	// regex is slow so we're doing it manually for a bunch of cases to maintain performance.

	if len(q) >= 10 && q[0:9] == "-- name: " {
		// -- name: {name} :{type}
		if index := strings.Index(q[9:], ":"); index != -1 {
			// remove leading space before :
			// optimised assuming this comment has been generated by SQLC
			return q[9 : 9+(index-1)]
		}
		// -- name: {name}
		if index := strings.Index(q[9:], "\n"); index != -1 {
			if q[len(q[9:9+index])-1] != ' ' {
				return q[9 : 9+index]
			}
			return strings.TrimSpace(q[9 : 9+index])
		}
	}

	if len(q) >= 9 && q[0:8] == "-- name:" {
		// -- name:{name}
		if index := strings.Index(q[8:], "\n"); index != -1 {
			if q[len(q[8:8+index])-1] != ' ' {
				return q[8 : 8+index]
			}
			return strings.TrimSpace(q[8 : 8+index])
		}
	}

	if len(q) >= 8 && q[0:7] == "--name:" {
		// -- name:{name}
		if index := strings.Index(q[7:], "\n"); index != -1 {
			if q[len(q[7:7+index])-1] != ' ' {
				return q[7 : 7+index]
			}
			return strings.TrimSpace(q[7 : 7+index])
		}
	}

	return ""
}
